/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- 5. Magnitude
-- Compare the measure values by categories.
-- It helps us understand the importance of different categories.
-- ∑[Measure]By[Dimension]
-- Find total numbers of customers by countries
SELECT   country, -- Dimension
         COUNT(customer_key) AS total_customers -- Measure
FROM     gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total numbers of customers by gender
SELECT   gender, -- Dimension
         COUNT(customer_key) AS total_customers -- Measure
FROM     gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total numbers of products by category
SELECT   category, -- Dimension
         COUNT(product_key) AS total_products -- Measure
FROM     gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT   category, -- Dimension
         AVG(cost) AS avg_costs -- Measure
FROM     gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the total revenue generated for each category?
SELECT   p.category,
         SUM(f.sales_amount) AS total_revenue
FROM     gold.fact_sales AS f
         LEFT OUTER JOIN
         gold.dim_products AS p
         ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT   c.customer_key,
         c.first_name,
         c.last_name,
         SUM(f.price) AS total_revenue
FROM     gold.fact_sales AS f
         LEFT OUTER JOIN
         gold.dim_customers AS c
         ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT   c.country,
         SUM(f.quantity) AS total_sold_items
FROM     gold.fact_sales AS f
         LEFT OUTER JOIN
         gold.dim_customers AS c
         ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- Those Dimension with few unique values are called Low Cardinality Dimension
-- For example: Category, Country, Gender
-- Those Dimension with large number of unique values are called High Cardinality Dimension
-- For example: Product, Customer, Address
